# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ec640c38f34c3788025211595ce558fbe93b656e2a90ae49505ff4c647d7f9830154212beae5b3db29d9da65f5608fc9727ca6180f0b3853923afcc3cc8ae1d

test:
  secret_key_base: 3a6d9ac749645c1e12d92917988d842e250be54fd49e80272beb5b982eb48e653e79a9717912d8190d80408a1b3fd83aee01027cef4004e245f6c1829d2af2a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
