# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b485a7504139220cec4c90e29e16024f4754f87d9a4abf444f8c954daeb2cae13f2d2991ea651e41b3f7e6b541d4bf83746f3e9342aeb6a4593d193cfdc7695

test:
  secret_key_base: b4c51326f64bf03b30654c708ea8e69bdb7356486b9901152f9d4099b9120dd967134e2d1866e2b91ab0915ce0b0ac70cb6a11464a46700ac3156aaa93001504

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
