# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c93e3a9fc28f4f69a1570cbb762c2050400c887906b58ee6371d19a82109cf17249c37f84630fafab4dc9b2441a52f47d4543c2e20a16947476f58b209c88c03

test:
  secret_key_base: 564769c727e7ffe9dfdf828895aae139ef16ce19bf7bd7c57f1cfaa4d4641319962d92ce07f27b3cb231e42c301d8987fa77635a0da4a9bcedd4da3176a54f81

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
