# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cbbabe2217d1c574ccf445d258a8b0014933b5ca05feeb4e8c2a8a4370985bdebbb8b0da5ff37808cb9dc6b0633268880693cc3fcafd406e48a2875675ab88af

test:
  secret_key_base: a87a83c80481a714da22c5bca65cc63eb0ca1e181e0ebeff619fcc46355e8d3ec5da653aa702b8be7064559527d75af2ac39b58fbc78aee2b5da8fc0639f08f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
